AZURE_OPENAI_API_KEY="3fa004bc77944da58806e4717699fb67"
AZURE_OPENAI_ENDPOINT="https://open-ai-hml.openai.azure.com"
AZURE_OPENAI_API_VERSION="2024-02-15-preview"
AZURE_OPENAI_DEPLOYMENT="gpt-4o"
AZURE_OPENAI_MODEL="gpt-4o"